version: "3.8"

services:
  python:
    image: python:latest-slim-bullseye
    container_name: python
    restart: always
    network:
      - "monitoring"


  influxdb:
    image: influxdb:latest
    container_name: influxdb
    volumes:
      - $PWD/data:/var/lib/influxdb
      - $PWD/config:/etc/influxdb
    ports:
      - 8086:8086
    restart: always
    network:
      - "monitoring"
    environment:
      #docker environment vars for influxdb
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=monitoring
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_MODE=setup

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - influxdb
    links:
      - influxdb
    restart: always
    network:
      - "monitoring"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    links:
      - influxdb
    restart: always
    ports:
      - 8092:8092/udp
      - 8094:8094

    network:
      - "monitoring"    